### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _GeoIP_id_by_ipnum

### ISSUE THREAD

**Issue by kuno** [maxmind/geoip-api-c#20]
I am the author of nodejs module [GeoIP](https://github.com/kuno/GeoIP).

Essentially, this is a c++ binding to `geoip-api-c` library.

Until version version 1.5.1, every thing works well.

But after updated to 1.5.2, I can still build successfully it on my macbook air , but when I do the  unit test.

The program crash with this error 

```
dyld: lazy symbol binding failed: Symbol not found: _GeoIP_id_by_ipnum
  Referenced from: /Users/kuno/Hub/kuno/GeoIP/build/Release/geoip.node
  Expected in: dynamic lookup

dyld: Symbol not found: _GeoIP_id_by_ipnum
  Referenced from: /Users/kuno/Hub/kuno/GeoIP/build/Release/geoip.node
  Expected in: dynamic lookup
```

This is really strange, because, as you guys probably know, there a function `GeoIP_id_by_ipnum` defined in `GeoIP.h`, but where this symbole `_GeoIP_id_by_ipnum` came from?
